name: Odoo-Docker-Deployment

services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - odoo-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    networks:
      - odoo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 30s
      timeout: 10s
      retries: 5

  odoo:
    image: odoo:17
    depends_on:
      - db
    restart: always
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - DATABASE=postgres
    volumes:
      - odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./etc/odoo.conf:/etc/odoo/odoo.conf
    networks:
      - odoo-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8069 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  odoo-network:

volumes:
  odoo-data:
  odoo-db:
