# -*- coding: utf-8 -*-
{
    'name': 'Late Check-In',
    'version': '17.1.3',
    'summary': """This module Allows Employee Late check-in deduction/penalty""",
    'description': """This module Allows Employee Late check-in deduction/penalty""",
    'author': "Prixite",
    'company': 'Prixite',
    'website': 'https://www.prixite.com',
    'maintainer': 'Prixite',
    'category': 'Human Resources',
    'depends': ['hr_attendance', 'hr_payroll', 'hr_contract'],
    'data': [
        'data/cron.xml',
        'views/res_config_settings.xml',
        'views/hr_attendance_view.xml',
        'views/late_check_in_view.xml',
        'views/early_checkout_views.xml',
        'views/hr_employee.xml',
        'security/ir.model.access.csv',
    ],
    'images': ['static/description/banner.png'],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
